"""Generate an honest, offline portfolio snapshot from actual model outputs."""
from html import escape
from pathlib import Path

from .model import predict_win_probability
from .retrieval import TfidfRetriever

DEMO_INPUT = {
    "notes": "Decision makers are engaged and requested a final analytics proposal.",
    "region": "Northeast", "industry": "technology", "customer_segment": "Mid-Market",
    "product_line": "analytics", "sales_stage": "proposal", "estimated_value": 75000,
    "days_in_pipeline": 52, "engagement_score": 78, "meetings_count": 5,
    "competitor_present": True, "discount_pct": 0.12, "proposal_sent": True,
}
DEMO_QUERY = "analytics proposal with executive engagement and an active competitor"


def write_preview(model, df, metrics: dict, path: Path) -> None:
    prediction = predict_win_probability(model, **DEMO_INPUT)
    hits = TfidfRetriever(df).search(DEMO_QUERY)
    rows = "".join(
        f"<tr><td>{escape(h.opportunity_id)}</td><td>{escape(h.industry)}</td>"
        f"<td>{escape(h.product_line)}</td><td>{escape(h.outcome)}</td><td>{h.score:.4f}</td></tr>"
        for h in hits
    )
    fields = "".join(
        f"<dt>{escape(key.replace('_', ' ').capitalize())}</dt><dd>{escape(str(value))}</dd>"
        for key, value in DEMO_INPUT.items()
    )
    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>AI Sales Pipeline Intelligence — reproducible snapshot</title>
<style>
*{{box-sizing:border-box}}body{{margin:0;background:#f2f5f8;color:#233044;font:16px/1.6 system-ui,sans-serif}}
main{{max-width:1080px;margin:auto;padding:40px 24px}}h1{{font-size:36px;line-height:1.2;margin:8px 0 18px}}
h2{{font-size:22px}}header{{margin-bottom:28px}}.label{{color:#416d0c;font-weight:700;letter-spacing:.1em;font-size:12px}}
.grid{{display:grid;grid-template-columns:1fr 1fr;gap:20px}}section,.metric{{background:white;border:1px solid #dce2e9;border-radius:14px;padding:24px;margin-bottom:20px}}
.metrics{{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}}.metric strong{{display:block;font-size:32px;color:#416d0c}}
.score{{font-size:64px;font-weight:800;color:#416d0c}}small,.muted{{color:#576779}}dl{{display:grid;grid-template-columns:1fr 1fr;gap:6px;font-size:14px}}dt{{color:#576779}}dd{{margin:0}}
table{{width:100%;border-collapse:collapse}}td,th{{padding:10px;text-align:left;border-bottom:1px solid #dce2e9;font-size:14px}}.table-wrap{{overflow:auto}}
footer{{font-size:13px;color:#576779}}@media(max-width:700px){{.grid,.metrics{{grid-template-columns:1fr}}}}
</style></head><body><main>
<header><div class="label">DATA &amp; AI ENGINEERING PORTFOLIO</div>
<h1>AI Sales Pipeline Intelligence</h1>
<p>Validated synthetic CRM data, probability estimates, historical retrieval, and evidence-based analysis.</p>
<p class="muted"><strong>Offline snapshot.</strong> Generated by <code>python -m src.evaluate</code>.
This page does not connect to an API or report live CI status. Use Streamlit for interactive inputs.</p></header>
<div class="metrics">
<div class="metric"><strong>{metrics['roc_auc']:.3f}</strong>Holdout ROC-AUC<br><small>95% row-bootstrap interval: {metrics['roc_auc_ci95'][0]:.3f}–{metrics['roc_auc_ci95'][1]:.3f}</small></div>
<div class="metric"><strong>{metrics['brier_score']:.3f}</strong>Brier score (lower is better)<br><small>Constant-probability baseline: {metrics['baseline']['brier_score']:.3f}</small></div>
<div class="metric"><strong>{metrics['test_rows']}</strong>Test opportunities<br><small>{metrics['split']['train_rows']} train / {metrics['split']['validation_rows']} validation</small></div>
</div><div class="grid"><section><h2>Reproducible input</h2><dl>{fields}</dl></section>
<section><h2>Model estimate</h2><div class="score">{prediction['win_probability']:.1%}</div>
<p>Prediction: <strong>{prediction['predicted_outcome'].upper()}</strong> at the default 50% decision threshold.</p>
<p>This is an estimate on a synthetic population. Validate calibration, timing, and intervention costs before using scores for commercial decisions.</p>
<p>Post-close outcome, revenue, and close reason are excluded from the model features.</p></section></div>
<section><h2>Retrieved historical evidence</h2><p>{escape(DEMO_QUERY)}</p><div class="table-wrap">
<table><thead><tr><th>ID</th><th>Industry</th><th>Product</th><th>Outcome</th><th>Lexical similarity</th></tr></thead><tbody>{rows}</tbody></table></div>
<p class="muted">Similarity is not a probability, a causal explanation, or a human relevance judgment.
Zero-overlap queries return no evidence; optional LLM outputs must cite supplied IDs.</p></section>
<section><h2>Engineering evidence</h2><p>Shared data and API validation; bounded inputs; email redaction;
disjoint train/validation/test partitions; probability-baseline comparison; confidence interval and calibration plot;
out-of-vocabulary abstention; LLM response validation; readiness checks; regression tests.</p>
<p>Optional Chroma behavior has client-contract tests. A live Chroma/embedding service, live Ollama model,
and Docker build require their own runtime checks. GitHub Actions runs tests and a container smoke test after a push.</p></section>
<footer>All records are synthetic. Generated metrics describe this benchmark only. No client deployment,
business impact, or live service status is claimed. Dataset fingerprint: {metrics['dataset_sha256']}</footer>
</main></body></html>"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
